# Generated by Django 5.0.1 on 2024-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                (
                    "imgfile",
                    models.ImageField(blank=True, null=True, upload_to="image/"),
                ),
            ],
        ),
    ]
